### ISSUE TITLE
withSession should work in SSR pages  too

### ISSUE THREAD

**Issue by vvo** [vvo/next-iron-session#10]
Just like https://github.com/hoangvvo/next-session#-withsession-

**Comment by hoangvvo** [comment]
I would also suggest steering toward the new [`getServerSideProps`](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) instead of `getIntialProps` since `getServerSideProps` is always server-side. However, the HOC model (like `withIronSession`) may not work.

**Comment by vvo** [comment]
linked pr: #23
