### ISSUE TITLE
Best Practice for using access token

### ISSUE THREAD

**Issue by jasonkw9** [vvo/next-iron-session#137]
Hi there, I am quite new to nextjs and JAMstack. The project I am building right now is using laravel as backend and Nextjs as front end, communicate through API. I am able to do a simple login and logout using the example given. Based on what I understand (using login as example here), after user press the login button, it will first go through api routes in Nextjs for example /api/login then only go the the backend API. Is this the best practice to go through two API for one function for CRUD as well? Or I can just use 'getStaticProps' or 'getServerSideProps' to get the access token then directly from there, call to the real API.

What I really want to know is that, is it really need to go through the Nextjs api route first?

**Comment by vvo** [comment]
@jasonkw9 I believe that if you're building your API with Laravel then you should not use any backend feature of Next.js but only use it as a frontend and rely on Laravel for everything backend. Otherwise, as you found out, you'll always make an extra request to Next.js only for authentication which will complexify things.

I am pretty sure there are "Laravel Next.js authentication" examples out there, did you check them out? This might be a better idea than trying to use next-iron-session which is more aimed towards people willing to build their frontend AND api using Next.js.

It seems like most people in the Laravel world are using Nuxt.js (Vue) instead of Next.js which might be another reason it could be hard for you to find the right way to do things Laravel + Next.js wise!

**Comment by jasonkw9** [comment]
@vvo Yes, I have been searching for any "Laravel Next.js authentication" related articles but no luck. However, now I am able to get the access token using getServerSideProps in edit.js for example. Then inside this edit.js, I can straight submit all the data to my laravel API with the token.

It's all work now, just that I am worried if this violates any security rules here?

**Comment by vvo** [comment]
Nice that you managed to do so. As for security I cannot provide you a good answer here without seeing you code BUT if your API can only be reached once logged in you should be fine yep!

**Comment by khake19** [comment]
hi @vvo , what if I use `iron-session` to encrypt the token coming from my backend service? Do you think this is a viable approach?

**Comment by amitleuva1987** [comment]
below is one of the solution available to use laravel as backend with next js frontend.

[https://larainfo.com/blogs/laravel-9-authentication-with-next-js-example](https://larainfo.com/blogs/laravel-9-authentication-with-next-js-example)

**Comment by wobsoriano** [comment]
Unrelated, but made a Nuxt module https://github.com/wobsoriano/nuxt-iron-session
