### ISSUE TITLE
req.session.get returning undefined

### ISSUE THREAD

**Issue by thecox** [vvo/next-iron-session#195]
Hi there,

I've been attempting to get a login system set up using sessions, but every time I attempt to get the data out of the `req.session`, it returns `undefined`. Finally, I just reverted back to the most basic example included in the README but get the same undefined. Here are what my files look like at this point:

```
import { withIronSession } from 'next-iron-session';

function handler(req, res, session) {
  const user = req.session.get('user');
  console.log(user);
  res.send({ user });
}

export default withIronSession(handler, {
  password: process.env.SECRET_COOKIE_PASSWORD,
  cookieName: 'test-cookie',
  cookieOptions: {
    secure: process.env.NODE_ENV === 'production'
  }
});
```

```
import { withIronSession } from 'next-iron-session';

async function handler(req, res) {
  // get user from database then:
  req.session.set('user', {
    id: 230,
    admin: true
  });
  await req.session.save();
  res.send('Logged in');
}

export default withIronSession(handler, {
  password: process.env.SECRET_COOKIE_PASSWORD,
  cookieName: 'test-cookie',
  cookieOptions: {
    secure: process.env.NODE_ENV === 'production'
  }
});
```

I haven't made any changes to the vanilla API set up for Nextjs up to this point, so not really sure what could be causing the issue. I'm even able to see the persistent cookie when printed in `getInitialProps` from one of the pages, just can't get to the data it contains.

Some further clarification, if it helps: I'm attempting to develop on localhost and have set the `secure: false` option.

I've been struggling with this for a solid day at this point and hoping you might be able to point me in the right direction. Thanks for your assistance!

**Comment by vvo** [comment]
Hey there, can you create a GitHub repository for me to try out your example?

Can you try to change the cookieName and see what happens?

Thanks

**Comment by thecox** [comment]
Thanks for getting back with me so quickly. I did some refactoring and was able to get everything up and running. I'm honestly not 100% sure what the issue was but accessing the session via `getServerSideProps` seems to have better results (similar to the provided example).

Anyway, appreciate this project as it's just about the only thing that will work with vercel without having to use an external session storage. I'll close it out and thanks again!

**Comment by dayvista** [comment]
Is there any way to fetch the session (using req.session.get) other than through getServerSideProps? I'd strongly prefer not to disable static generation for my entire app in order to fetch the session. In looking at the README for [next-session](https://github.com/hoangvvo/next-session), it says (in the soon to be deprecated getInitialProps example) that "req.session is only available on server-side" and "On client-side routing, neither req nor req.session is available.".

I guess I'm not understanding why the session cookie can't be fetched through an API call on the client side. I'm also curious as to why this isn't mentioned in the docs, unless it's assumed that the API routes defined in the docs/README are only meant to be used in getServerSideProps.
