### ISSUE TITLE
Unable to fetch session if I call API using fetch in Next.js

### ISSUE THREAD

**Issue by ankursingh0313** [vvo/next-iron-session#301]
I have created a **Next.js** project and, I'm using following code to call api,
```
export const getServerSideProps = withIronSession(
	async ({req, res}) => {
		const { client } = await connectToDatabase()
		const isConnected = await client.isConnected()
		const r = await fetch("http://localhost:3000/api/s", {
				method: "GET",
				headers: { "Content-Type": "application/json" },
			});
		return {
			props: { isConnected: isConnected, user:r.email?r.email:"" },
		}
	},
	{
		cookieName: process.env.MYSITECOOKIE,
		cookieOptions: {
			secure: process.env.NODE_ENV === "production" ? true : false
		},
		password: process.env.SESSION_PASSWORD
	}
);
```
If I directly call this api (http://localhost:3000/api/s) then it shows user, but when I call using fetch it doesn't return the result.

**Comment by vvo** [comment]
Hey there, you're trying to call an API from getServerSide props, which means this call to localhost will be made by your SERVER. This is not the way to use next-iron-session + getServerSideProps (here's how to do it: https://github.com/vvo/next-iron-session/blob/master/examples/next.js/pages/profile-ssr.jsx#L35)

When you call localhost in getServerSideProps, cookies are not sent (because the server has no cookies).

I suggest you use something like https://github.com/vercel/swr to make calls to your API from your frontend instead.
