### ISSUE TITLE
Need to understand what is the difference between this library approach and "normal" JWT in local storage

### ISSUE THREAD

**Issue by zoamel** [vvo/next-iron-session#348]
Hi everyone!

I and my friend have recently started our new side project with Next.js on the frontend and Nest.js (Express) in the backend. I started with implementing REST API with JWT Auth, using a common approach with getting token via Bearer in the headers.

And this is where problems started to occur 🙂

I started reading about what is recommended approach for handling authentication in the Next.js app, and all of the documentation and articles told me to use either next-auth or iron-session or some 3rd party like firebase and auth0. I am interested in keeping everything under our control, so at this point, I was left with 2 first approaches.

As I understand having a cookie session with httpOnly is more secure than having it stored in the local storage. But apart from that, I have few questions that about things that are not clear to me.

Apart from security, why is this approach better than the more common one with local storage? I mean in a situation when I have multiple public pages, which don't need authentication and only a few to which you should be logged in. I assume, since the private pages can be client-side only, we could skip the additional hassle of handling cookies.

Another head-scratching part is how to handle "normal" HTTP requests to our REST API which will be in completely different places and URL. All of the tutorials I've found use Next.js API routes to handle authentication, which I am ok with. But how to use this approach to call external API and pass token to it? Should I proxy all the calls via Next.js API routes, in that case, extract the token from iron-session and attach it to the API request? Or should I change the API authentication implementation to use httpOnly cookie, but in that case how to connect it with iron-session?

If you could point to some example project/code, it would be awesome 🙂

**Comment by vvo** [comment]
Hey there!

> Need to understand what is the difference between this library approach and "normal" JWT in local storage

JWT is a standard, while next-iron-session tokens are not a standard. JWT tokens are unencrypted (you need JWE if you want them encrypted). Do you need encryption? Depends on your usecase. Unencrypted does not mean people can trick you and change their JWT (they can't, JWT are signed so the signature would not match the new content).

I think that summarizes it well. When you use JWT you can store tokens in cookies or in local storage, up to you. As for using cookies or localstorage, I am no expert either so I just read on the internet for discussions like https://stackoverflow.com/questions/27067251/where-to-store-jwt-in-browser-how-to-protect-against-csrf or https://programarivm.com/how-to-store-jwt-and-oauth-access-tokens-as-per-owasp-guidelines.

For next-iron-session we went for cookies because it's the easiest (from our POV): tokens are sent to endpoints automatically by the browser, no need to read it from somewhere and add it to calls, it's automatic.

> But how to use this approach to call external API and pass token to it? Should I proxy all the calls via Next.js API routes, in that case, extract the token from iron-session and attach it to the API request? Or should I change the API authentication implementation to use httpOnly cookie, but in that case how to connect it with iron-session?

Re: JWT is a standard. When you use JWTs you can easily read those from any programming language, any framework, just need a JWT reader and your secret keys used. When using next-iron-session, if you use Node.js you can decode those tokens with https://github.com/vvo/iron-store (I think someone did that in another issue, here: https://github.com/vvo/next-iron-session/issues/295#issuecomment-827218157)

Given your requirements, I would advise you to use https://next-auth.js.org/ with JWTs and call your API endpoint (no need for proxying, just need the right CORS options).

Goodluck!
