### ISSUE TITLE
typescript: typing for withIronSession handler is wrong

### ISSUE THREAD

**Issue by akomm** [vvo/next-iron-session#368]
`withSession`'s handler is typed to get request as first argument, but when using `getServerSideProps` the first argument is `context` with `req` property. The example ssr-profile ignores the typing and destructures the context, for (type-wise) undefined property req.

**Comment by akomm** [comment]
I think the whole typescript typing on `withIronsession` `handler` does not make any sense.

**Comment by vvo** [comment]
Hey there @akomm thanks for jumping in, the TypeScript situation of next-iron-session has been tricky since the beginning mostly I guess because of the way it is written (modify req object).

If you have any ideas on how to improve this situation then you can either:
- create a new type at https://github.com/DefinitelyTyped/DefinitelyTyped (preferred) and experiment with it. As soon as it is working perfectly then we could merge it here directly
- try to modify/update the current types of this repository (not recommended), but this could get very tricky since multiple people already tried it.

Thanks and good luck!

**Comment by ApacheEx** [comment]
Hello,
I faced the same problem when looking on typescript example:


Currently, I've solved it in the following way:

`lib/session.ts`
![image](https://user-images.githubusercontent.com/1918108/127736296-277a5a15-0100-4222-a307-265bda86256b.png)


and when you use `getServerSideProps`, you should simply add a custom type which stands for SSR from the `session.ts`:

`pages/whatever.ts`
![image](https://user-images.githubusercontent.com/1918108/127736084-2324315c-6e29-472f-bf4d-94af8a72bd6f.png)

**Comment by Matt319** [comment]
@ApacheEx that solution worked for me and solved my problem. Thanks for sharing!

**Comment by vvo** [comment]
Hey there, the typings were fully redone as part of the V6. Changelog here: https://github.com/vvo/iron-session/releases/tag/v6.0.0

**Comment by vvo** [comment]
It should be a lot better now
