### ISSUE TITLE
Automatically renew sessions?

### ISSUE THREAD

**Issue by vvo** [vvo/next-iron-session#85]
**Update: Yes we should do it, taking ideas and PR on this issue, thanks**

Should we automatically refresh/touch/renew sessions? For example every time the session is saved we should make sure the cookie expiration time is pushed further.

We should also provide examples where calling .save() would be beneficial (like when user logs in?)

Production usage will provide better insights, comment if you have some!

**Comment by joshuabaker** [comment]
We’re not yet in production, but arrived here by wondering about this. So, yes, there’s interest in an example. 

Will report back with any further thoughts.

**Comment by mwisner** [comment]
Out of scope of the conversation, and I don't know if this is a good personal decision or not, so take this with a grain of salt...

I was looking to have the session expire along with another cookie at the same time. So while I'm personally not looking for automatic renewal I am curious to figure out how to update an existing session with a specific expiration date/time.

**Comment by vvo** [comment]
@mwisner can you open another GitHub issue with your detailed usecase?

**Comment by dayvista** [comment]
As per @joshuabaker - we'll be entering production soon and are curious about this feature. I see that req.session.save() has no content in the README. Wondering what the status of this is.

**Comment by KupGest** [comment]
@vvo might be a bit late to the conversation, but the current work around this (at least for me) is to run the save() which sets the session all over again.

**Comment by vvo** [comment]
Hey there. Renewing sessions automatically is tricky because we have to decide "when" to renew the session automatically.

Also, automatically renewing the session means practically infinite sessions. And if you're looking to do that then using the option ttl = 0 will achieve the same in the next version of iron session. The cookie will be set to 10 years by default. The is the maximum browsers are willing to accept.

You could also set the session as a "session cookie", most browsers will (unfortunately) consider session cookies as unlimited and reuse them for as long as possible (see https://bugs.chromium.org/p/chromium/issues/detail?id=128513).

What I've witnessed from production usage is that I don't need to renew sessions automatically. This gets done by default as soon as I modify the session. So if a user do not interact with my website for more than 14 days (the default) then the cookie expires. But that's a good thing from my point of view.

Decision: will not implement but provide alternatives (session cookies or very long sessions). Good luck!

**Comment by hidaloop** [comment]
Hello!
I understand that this issue is closed, and my comment might not be as relevant for this thread anymore. But in case someone like me roaming around issues in search of answers to session renewal, I would like to share my method for tracking users activity, and session renewal.

The idea is to simply encode `creationTime` or `updateTime` inside the session, and provide a middleware, which works accordingly with this time =)

For instance, in my case, the session is pretty much needs to be set only at the login step. However, for smooth work, I would not want my users to suddenly logout during a consecutive request (although smoothness might be handled client side), which happens on expiration boundary.

Thus a middleware compares creation time, and current time, and decides whether the session should be updated consequently extending the life of a session.

**Comment by villesau** [comment]
@vvo it is pretty standard behaviour in at least express session, see: https://github.com/expressjs/session?tab=readme-ov-file#rolling

https://github.com/expressjs/session/blob/24d4972764d2c962f806c38357f257cf97081009/index.js#L478
