### ISSUE TITLE
Trying an undocumented scenario

### ISSUE THREAD

**Issue by Dashue** [vvo/next-iron-session#86]
Hey @vvo  and thanks for all your work on this.

I'm struggling with a use-case which may or may not be supported.

I've got a profile page
```
export const getServerSideProps: GetServerSideProps = withSession(
    async ({ req }) => {

        console.log(req.session.get('user')) // This is properly set here
        let studio;
        try {
            studio = await axios.get<any>(GetUrl('/user/studioprofile'));
        }
        catch {
            // silence
        }

        return {
            props: {
                studio
            }
        }
    }
);
```

This page is trying to preload from a protected userprofile endpoint

```
const handler = async (req: SessionRequest, res: NextApiResponse) => {
    console.log(req.session) // req.session exists
    console.log(req.session.get('user')) // user is undefined

    res.status(401);
    res.end();
}
```

But in the api the user does not exist. The session is there wth get,set etc functions.

When I check the api in the browser it works.
I'm guessing this is because browser sends cookie, but my getserversideprops does not?
I tried the old withCredentials:true option to axios blindly, but didn't work.

I think this is a use-case not covered in your examples, and perhaps isn't supported?

Thanks for your help!

**Comment by vvo** [comment]
Hey there, would you be able to create a reproducible example in a GitHub repo so I can have a look? Thanks!

**Comment by Dashue** [comment]
I'm not able to reproduce in the example code.
Weird this is copying the sample code straight into my nextjs site 1:1 also does not work.

Is there anything that can interfere as far as you know?

Happy to give access to the source repo if that helps?

**Comment by Dashue** [comment]
Hmm for some reason my req.cookies in the api are empty but they get sent over in your nextjs sample.
Found this:  https://github.com/zeit/next.js/issues/9874
Where Tim states

> This is not a bug. fetch doesn't send cookies by default.
> https://github.com/github/fetch#sending-cookies
> When doing SSR you have to manually pass cookies along from the request.
> something like
> headers: { Cookie: req.headers['Cookie'] }

So I guess my question has evolved to, why does the sample work without it?
Perhaps some magic of swr?

Both these work
```
const resp = await fetch('http://localhost:3000/api/profile', { headers: { Cookie: req.headers.cookie } });

const resp = await Axios.get('http://localhost:3000/api/profile', { headers: { Cookie: req.headers.cookie } });
```

**Comment by vvo** [comment]
The issue I think is that your localhost is in HTTP (not HTTPS) and the library has the "secure" flag by default. See the new examples:

```
export default withIronSession(handler, {
  password: "complex_password_at_least_32_characters_long",
  // if your localhost is server on http:// then disable the secure flag
  cookieOptions: {
    secure: process.env.NODE_ENV === "production" ? true : false,
  },
});
```

I guess now I need to do this: #8

**Comment by Dashue** [comment]
Have 
secure: false,
sameSite: 'strict',
httpOnly: false,

I think it's an issue with axios possibly, "Refusing to set unsafe cookie"

I guess it's all for the good, it's makes sense that next doesn't throw over cookies on ssr. I just need to manually include the headers I guess

**Comment by vvo** [comment]
@Dashue re-reading your initial example: you have a getServerSideProps call doing an axios call. And you expect cookies from getServerSideProps to be sent to axios. This cannot work because getServerSideProps is happening on the server side (Node.js), so cookies will never be forwarded there. On the browser, whenever you do a call to another server then cookies are sent automatically.

The part in fetch about cookies is for cross site requests, so doing a call from a.com to b.com you won't receive cookies from b.com (if I understood it well :D)

![image](https://user-images.githubusercontent.com/123822/81007820-3112ce80-8e52-11ea-809e-1e735ef58c92.png)

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

Fetch does send cookies by default if you call a.com/api from a.com/page directly. But if you do the call from your server to a.com/api then things are different and you need to find the right combination of your HTTP library to do it)

In my Next.js example of this repository, I do not make a call to another server with cookies inside, I only call GitHub and then set-cookie to the user that made the request to the example's Next.js server.

**For your current issue:**

1. Why not just make the call from the browser to the API?
2. It seems the issue https://github.com/axios/axios/issues/319 can help
3. Otherwise, try https://github.com/sindresorhus/got which is more active than axios nowadays I believe.

good luck!

**Comment by Dashue** [comment]
The weird thing was I got your example to work that way when both you and I think it shouldn't :)

Must have been something else interferring, manually providing the cookie header works when getserversideprops calls api.
